# Site settings
title: StorageOS Documentation
email: info@storageos.com
description: Guides, tutorials and reference documentation for StorageOS, converged storage for containers.
baseurl: ""
url: "https://docs.storageos.com"

exclude: ["Dockerfile", "Dockerfile.dapper", "Makefile", "README.md"]

latest_node_version: 1.1.1
latest_cli_version: 1.0.0

# Build settings
permalink: :module
incremental: false
highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 html_to_native: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  docs:
    output: true
  guides:
    output: true
  reference:
    output: true
  samples:
    output: true
  support:
    output: true

plugins:
  - jekyll-redirect-from
