# Site settings
title: StorageOS Documentation
email: info@storageos.com
description: Guides, tutorials and reference documentation for StorageOS, converged storage for containers.
baseurl: ""
url: "https://docs.storageos.com"

exclude: ["Dockerfile", "Dockerfile.dapper", "Makefile", "README.md"]

# Google services
google_analytics: UA-70625114-1

# Build settings
incremental: true
highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 html_to_native: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  docs:
    output: true
  guides:
    output: true
  reference:
    output: true
  samples:
    output: true
  support:
    output: true
